name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./taskflow
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Dependencies 🔧
        run: pnpm install --no-frozen-lockfile

      - name: Build Project 🏗️
        run: pnpm run build

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: taskflow/dist
          branch: gh-pages
